In [1]:
import numpy as np

In [2]:
tinggi  = [1.7,1.8,1.9,1.10,1.11,1.12]
berat   = [1,2,3,4,5,6,7,8,9,]

In [8]:
np_tinggi= np.array(tinggi)
np_berat = np.array(berat)

np_berat/np_tinggi

SyntaxError: invalid syntax (2586768270.py, line 6)

In [ ]:
np.arrange(5)

AttributeError: module 'numpy' has no attribute 'arrange'

In [ ]:
print(np.arange(3,10,2))

[3 5 7 9]


In [ ]:
arr = np.array([1,2,3,4])
arr_new= np.append(arr,[7,8,9])

In [ ]:
arr_new

array([1, 2, 3, 4, 7, 8, 9])

In [ ]:
np.delete(arr_new,3)

array([1, 2, 3, 7, 8, 9])

In [ ]:
#0-D Skalar

arr= np.array(6)
print(arr)

6


In [ ]:
#mengecek dimensi
arr.ndim

0

In [ ]:
arr.shape #melihat baris

()

In [ ]:
#1-D/Vektor
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [ ]:
arr.ndim

1

In [ ]:
arr.shape

(4,)

In [ ]:
#2-D/Matriks
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
arr=np.array([[[1,2,3,4],[5,6,7,8],[5,6,7,8]]])
print(arr)

[[[1 2 3 4]
  [5 6 7 8]
  [5 6 7 8]]]


In [ ]:
arr.ndim

3

In [ ]:
arr.shape

(1, 3, 4)

In [ ]:
arr.size

12

In [ ]:
arr=np.arange(6)
print(arr)

[0 1 2 3 4 5]


In [ ]:
matriks= arr.reshape(3,2)
print(matriks)

[[0 1]
 [2 3]
 [4 5]]


In [ ]:
a = np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [ ]:
a.shape

(6,)

In [ ]:
a2= a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [ ]:
a3=a[:, np.newaxis]
print(a3.shape)
print(a3)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [ ]:
a_e=np.expand_dims(a,axis=1)#menambahkan 1 dimensi
a_e.shape

(6, 1)

In [ ]:
#SOAL

arr= np.array([1,2,7,4,10,5,13,11])
print(arr[2:8:3])

[7 5]


In [ ]:
arr= np.array([1,2,7,4,10,5,13,11])
print(arr[:8:3])

[ 1  4 13]


In [ ]:
arr=np.array([[1,2,3,4,8,10],[5,6,7,8,7,10],[9,10,11,12,11,12]])
print(arr[:4:2,2])
print(arr[1:2,2:3])

[ 3 11]
[[7]]


In [ ]:
print(arr[2,2:4])

[11 12]


In [ ]:
arr_new=np.array([1,2,3,4,5,6,7,8,9,10,11,12]) #unknown dimension
new_arr = arr_new.reshape(2,3,-1)
print(new_arr.shape)
print(new_arr)


(2, 3, 2)
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
