Apakah $\begin{bmatrix}1 \3\end{bmatrix}$ adalah eigenvector dari $\begin{bmatrix}1 & -1\6 &-4 \end{bmatrix}$? Jika iya, berapakah eigenvalue-nya?

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [156]:
a = np.array([1,3]).reshape(1,-1)

In [157]:
b = np.array([[1,-1],
             [6,-4]])
b

array([[ 1, -1],
       [ 6, -4]])

In [161]:
def plot_vector2d(vector2d, origin=[0, 0], **options):
    return plt.arrow(origin[0], origin[1], vector2d[0], vector2d[1],
              head_width=0.2, head_length=0.3, length_includes_head=True,
              **options)

### **APAKAH X ADALAH EIGEN VECTOR Y**

In [181]:
c=a*b
c

array([[  1,  -3],
       [  6, -12]])

### **Eigen Value**

In [182]:
eig_val, eig_vec = np.linalg.eig(c)

In [183]:
eig_val

array([ -0.5755711, -10.4244289])